In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6511, 6879, 9903, 7463],
 [6511, 6879, 9903, 9175],
 [6511, 6955, 9903, 730],
 [9847, 734, 3870, 519, 3479],
 [9847, 734, 3870, 519, 2495],
 [6631, 6511, 9264, 9903, 4175],
 [3802, 8948, 3468, 519]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6511 6879 9903 7463]
 [   0    0    0    0 6511 6879 9903 9175]
 [   0    0    0    0 6511 6955 9903  730]
 [   0    0    0 9847  734 3870  519 3479]
 [   0    0    0 9847  734 3870  519 2495]
 [   0    0    0 6631 6511 9264 9903 4175]
 [   0    0    0    0 3802 8948 3468  519]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\moham\Documents\Simple_RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step


array([[[ 2.83964165e-02, -2.14381944e-02, -2.47539766e-02,
          4.80248369e-02,  9.54394415e-03, -1.56614184e-02,
          3.73695381e-02, -4.83937524e-02,  4.72700112e-02,
          3.89969088e-02],
        [ 2.83964165e-02, -2.14381944e-02, -2.47539766e-02,
          4.80248369e-02,  9.54394415e-03, -1.56614184e-02,
          3.73695381e-02, -4.83937524e-02,  4.72700112e-02,
          3.89969088e-02],
        [ 2.83964165e-02, -2.14381944e-02, -2.47539766e-02,
          4.80248369e-02,  9.54394415e-03, -1.56614184e-02,
          3.73695381e-02, -4.83937524e-02,  4.72700112e-02,
          3.89969088e-02],
        [ 2.83964165e-02, -2.14381944e-02, -2.47539766e-02,
          4.80248369e-02,  9.54394415e-03, -1.56614184e-02,
          3.73695381e-02, -4.83937524e-02,  4.72700112e-02,
          3.89969088e-02],
        [-1.78309307e-02, -4.52556871e-02, -4.15460840e-02,
          9.65474918e-03,  3.94544713e-02, -1.66599266e-02,
          1.74858309e-02, -1.25818327e-03, -4.815638

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6511, 6879, 9903, 7463], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None